version: "3"
services:

  backend:
    build:
      context: ./ecommerce-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=itsasecret

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge